# Generated by Django 4.2.4 on 2023-09-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordenadas', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('satelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapas.satelite')),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapas.tipo_imagen')),
            ],
        ),
    ]
