# Generated by Django 4.2.4 on 2023-09-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='ImagenSatelital',
        ),
    ]
