# Generated by Django 4.2.4 on 2023-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_subimagensatelital'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensatelital',
            name='imagen_procesada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/procesada/'),
        ),
        migrations.AddField(
            model_name='subimagensatelital',
            name='coordenadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
