# Generated by Django 4.2.2 on 2024-01-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0005_imagensatelital_imagen_procesada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagensatelital",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="imagensatelital",
            name="imagen_procesada",
        ),
        migrations.RemoveField(
            model_name="subimagensatelital",
            name="coordenadas",
        ),
        migrations.AddField(
            model_name="subimagensatelital",
            name="porcentaje",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
