# Generated by Django 4.2.2 on 2024-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0006_remove_imagensatelital_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subimagensatelital",
            name="anio_imagen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
